### PR TITLE
Adding support for Centos for source compliation recipe

### PR DESCRIPTION
**Pull request by SinisterLight**

### CODE REVIEW

**Comment by SinisterLight** [comment]
Issue #3

**Comment by benlangfeld** [comment]
Thanks for this. I've already been doing this work yesterday and today, and what I have is more complete than this, so I'll finish off mine and see what you think is missing.

As for the Vagrantfile, that's what test kitchen is for :)

**Comment by SinisterLight** [comment]
I agree a lot more need to be done. I will wait for you changes then :)

**Comment by benlangfeld** [comment]
The develop branch now has CentOS support for source and package builds. The CI build to confirm that's working is at http://ci.mojolingo.com/job/FreeSWITCH%20Cookbook/18/.

I'm going to close this. Please try out the develop branch and let me know what you think.

**Pull request closed without merging**
